# Generated by Django 5.0 on 2023-12-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_no",
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
