# Generated by Django 5.0 on 2024-02-25 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MainApp", "0002_message"),
        ("MainApp", "0002_userprofile_phone_no"),
    ]

    operations = []
