name: Django CI

on:
  push:
    branches:
      - IsratEva

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run Migrations
      run: python manage.py migrate

    - name: Run Tests
      run: python manage.py test

    # Add more steps for linting, security scans, etc.
