      - name: Print current directory
        run: pwd

      - name: Run migrations and tests
        run: |
          cd OnlineBankingManagement
          python manage.py migrate
          python manage.py test
