name: sayma

on:
  push:
    branches:
      - Sayma

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Set Django Settings Module
        run: export DJANGO_SETTINGS_MODULE=OnlineBankingManagement.settings

      - name: Run migrations
        run: |
          cd OnlineBankingManagement
          python manage.py migrate

      - name: Run tests
        run: |
          cd OnlineBankingManagement
          python manage.py test
